apiVersion: skaffold/v1beta15
kind: Config
build:
  tagPolicy:
    sha256: {}
  # defines where to find the code at build time and where to push the resulting image
  artifacts:
  - context: src
    image: dotnet-hello-world
  - context: sidecar
    image: dotnet-monitor
# defines the Kubernetes manifests to deploy on each run
deploy:
  kubectl:
    manifests:
    - kubernetes-manifests/**
